### ISSUE TITLE
Make load wav accept a buffer instead of path

### ISSUE THREAD

**Issue by lundmark** [RandyGaul/tinysound#1]
This is generally a much better idea since not everyone who will use your api will be wanting to load stuff from disk. If you just let them provide you a buffert then they can pick if they want file-loading or memory-streaming or whatever.

Really nice API btw :)

**Comment by RandyGaul** [comment]
Hey good idea, thanks for the comment Simon! I'll make another version in the coming days :) Glad you liked the API, put quite a bit of work into it :)

**Comment by RandyGaul** [comment]
Done! Added stb_vorbis code for from-memory too (Sean had a convenient from mem function ready to go).

**Comment by lundmark** [comment]
Nice!
